Lesson_5/mainapp/goods/urls.py
from django.urls import path

from goods.views import GoodListView

app_name = 'products'

urlpatterns = [
    path('', GoodListView.as_view(), name='index'),
    path('category/<int:category_id>/', GoodListView.as_view(), name='categories'),
]

Lesson_5/mainapp/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls', namespace='goods')),
]

Lesson_5/mainapp/goods/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)


class Good(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False)
    receipt_date = models.DateTimeField(auto_now_add=True)
    price = models.PositiveIntegerField(default=0)
    unit = models.CharField(max_length=20)
    vendor_name = models.CharField(max_length=256, null=False, blank=False)
    good_category = models.ManyToManyField(Category)

Lesson_5/mainapp/goods/views.py
from django.shortcuts import render
from django.views.generic import ListView
from goods.models import Good, Category

# Create your views here.


class GoodListView(ListView):
    model = Good
    template_name = 'goods/goods_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        filter_cat = self.kwargs.get('category_id', None)
        if filter_cat:
            self.set_category_filter(filter_cat)
        context = super(GoodListView, self).get_context_data()
        context['title'] = 'GeekShop - Каталог'
        context['categories'] = Category.objects.all()
        context['filter'] = filter_cat
        return context

    def set_category_filter(self, filter_cat):
        self.object_list = Good.objects.filter(good_category=filter_cat)

Lesson_5/mainapp/goods/templates/goods/goods_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-4">
            <table class="table table-bordered">
                <thead>
                <tr class="table-primary">
                    <th>Категория товара</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <a href="{% url 'goods:index' %}"
                           class="list-group-item">Все категории</a>
                    </td>
                </tr>
                {% for category in categories %}
                    <tr>
                        <td>
                            <a href="{% url 'goods:categories' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="col-lg-4">
            <table class="table table-bordered">
                <thead>
                <tr class="table-primary">
                    <th>Название</th>
                    <th>Дата поступления</th>
                    <th>Цена</th>
                    <th>Единица измерения</th>
                    <th>Поставщик</th>
                </tr>
                </thead>
                <tbody>
                {% for product in object_list %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <td>{{ product.receipt_date }}</td>
                        <td>{{ product.price }}</td>
                        <td>{{ product.unit }}</td>
                        <td>{{ product.vendor_name }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

Lesson_5/mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock %}
</head>
<body>
<!-- Page Content -->
{% block content %}{% endblock %}
</body>

</html>